# Generated by Django 5.2.17 on 2026-09-01 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_actuelle', models.CharField(choices=[('inscription', 'Inscription'), ('verrouille', 'Verrouillage'), ('teasing', 'Teasing'), ('revelation', 'Révélation finale')], default='inscription', max_length=20)),
                ('date_fermeture_inscriptions', models.DateTimeField(blank=True, null=True)),
                ('date_heure_teasing', models.DateTimeField(blank=True, null=True)),
                ('date_heure_revelation', models.DateTimeField(blank=True, null=True)),
                ('revelation_declenchee_manuellement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Paramètre de l'événement",
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L3', 'L3')], max_length=2)),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('G', 'Masculin')], max_length=1)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('a_valide_questionnaire', models.BooleanField(default=False)),
                ('est_eligible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant(e)',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['niveau', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Un bon parrain doit être un modèle de réussite scolaire.')),
                ('q2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name="J'avoue mes lacunes à un aîné pour qu'il m'aide.")),
                ('q3', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Je préfère un parrain strict sur les révisions.')),
                ('q4', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Je veux aider mon match sur mes points forts.')),
                ('q5', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Mon parrain me fait découvrir les bons plans autour de la fac.')),
                ('q6', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Je suis partant pour des révisions en binôme.')),
                ('q7', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Une séance café/discussion me semble indispensable.')),
                ('q8', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Je préfère les activités de groupe.')),
                ('q9', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Les L3 apportent une maturité précieuse aux L1.')),
                ('q10', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name="Les différences d'âge sont un atout.")),
                ('q11', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name="Je suis à l'aise pour parler de mon orientation avec un L3.")),
                ('q12', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Sorties improvisées (5) ou soirées jeux tranquilles (1).')),
                ('q13', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Prêt à relever un défi farfelu si mon match me le lance.')),
                ('q14', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Bibliothèque silencieuse (1) ou foyer bruyant (5).')),
                ('q15', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name="Les amitiés naissent d'une entraide scolaire.")),
                ('date_soumission', models.DateTimeField(auto_now=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='parrainage.etudiant')),
            ],
            options={
                'verbose_name': 'Réponse au questionnaire',
                'verbose_name_plural': 'Réponses aux questionnaires',
            },
        ),
        migrations.CreateModel(
            name='DemandeForcage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Acceptée'), ('refuse', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('cible', models.ForeignKey(limit_choices_to={'niveau': 'L1'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='parrainage.etudiant')),
                ('demandeur', models.ForeignKey(limit_choices_to={'niveau': 'L3'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_emises', to='parrainage.etudiant')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_demande'],
                'unique_together': {('demandeur', 'cible')},
            },
        ),
    ]
