# Generated by Django 5.2.17 on 2026-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0002_alter_etudiant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Un bon parrain doit être un modèle de réussite scolaire.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="Les différences d'âge sont un atout."),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="Je suis à l'aise pour parler de mon orientation avec un L3."),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Sorties improvisées (5) ou soirées jeux tranquilles (1).'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Prêt à relever un défi farfelu si mon match me le lance.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Bibliothèque silencieuse (1) ou foyer bruyant (5).'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="Les amitiés naissent d'une entraide scolaire."),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="J'avoue mes lacunes à un aîné pour qu'il m'aide."),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Je préfère un parrain strict sur les révisions.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Je veux aider mon match sur mes points forts.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Mon parrain me fait découvrir les bons plans autour de la fac.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Je suis partant pour des révisions en binôme.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Une séance café/discussion me semble indispensable.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Je préfère les activités de groupe.'),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Les L3 apportent une maturité précieuse aux L1.'),
        ),
    ]
