# Generated by Django 5.2.17 on 2026-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0003_alter_reponsequestionnaire_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(blank=True, max_length=10, verbose_name='Groupe / classe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='identifiant',
            field=models.CharField(blank=True, help_text='Généré automatiquement pour la connexion des étudiants.', max_length=32, null=True, unique=True, verbose_name='Identifiant de connexion'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe_deduit',
            field=models.BooleanField(default=False, verbose_name='Sexe déduit (à vérifier)'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('G', 'Masculin')], max_length=1),
        ),
    ]
