# Generated by Django 5.2.17 on 2026-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0004_etudiant_groupe_etudiant_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, help_text="Une photo récente et reconnaissable. Recommandée : elle apparaît sur l'écran de révélation.", null=True, upload_to='photos/', verbose_name='Photo de profil'),
        ),
    ]
