# Generated by Django 5.2.17 on 2026-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0005_etudiant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='reponsequestionnaire',
            name='q9',
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='donnees',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='verrouille',
            field=models.BooleanField(default=False),
        ),
    ]
